version: '3'
 
services:
 app:
   image: fitastic/fitastic
   container_name: app
   restart: always
   ports:
     - 3000:3000
   deploy:
     resources:
       reservations:
         devices:
         - capabilities: [gpu]